set_property SRC_FILE_INFO {cfile:/home/y/fpga/2021.2/project_12/project_12.srcs/constrs_1/new/pcie.xdc rfile:../../../project_12.srcs/constrs_1/new/pcie.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD4                    [get_ports {pci_express_x4_txp[0]}]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE6                    [get_ports {pci_express_x4_txp[1]}]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG6                    [get_ports {pci_express_x4_txp[2]}]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH4                    [get_ports {pci_express_x4_txp[3]}]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE2                    [get_ports {pci_express_x4_rxp[0]}]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF4                    [get_ports {pci_express_x4_rxp[1]}]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG2                    [get_ports {pci_express_x4_rxp[2]}]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ2                    [get_ports {pci_express_x4_rxp[3]}]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB8                    [get_ports {pcie_refclk_clk_p[0]}]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L8                     [get_ports pcie_perstn]
